//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoAnMonHoc
    {
        public string ID { get; set; }
        public string MaMonHoc { get; set; }
        public string TenDeTai { get; set; }
        public string TienDo { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Check { get; set; }
        public Nullable<double> Diem { get; set; }
        public string MSSV { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
