//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TienDo
    {
        public string IDDeAn { get; set; }
        public string BaoCao { get; set; }
        public string HoanThanh { get; set; }
        public string LinkTaiLieu { get; set; }
        public Nullable<int> SoBuoi { get; set; }
    
        public virtual DeAn DeAn { get; set; }
    }
}
